### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by karx1** [joshiemoore/snakeware#110]
Whenever I try to build an image, it fails during compilation of `host-cdrkit`.

Entire output is [here.](
https://mystb.in/IndividualThatShortly.php)

**Comment by joshiemoore** [comment]
I had the same problem, this is a bug in GCC 10. The current solution is to downgrade to GCC 9.x. See the last few comments of #98 .

You'll have to do a `make clean` and start the build over once you downgrade GCC or it will cause problems.

**Comment by Admicos** [comment]
> You'll have to do a `make clean` and start the build over once you
> downgrade GCC or it will cause problems.

You don't need to `make clean`. Removing
`buildroot/output/build/host-cdrkit` (and possibly
`$HOME/.cache/snakeware-buildroot` should be enough.

Running `make clean`, unless you have a good CPU, will make you sad, as
cdrkit is one of the very last pieces to get built.

**Comment by karx1** [comment]
Yep, you just have to delete those directories and then it will work. Just did for me.

**Comment by joshiemoore** [comment]
There are numerous packages that get built after cdrkit. When I didn't do a clean before finishing the build the generated images had a lot of problems. It's a bad idea to build some of your packages with GCC 9 and some with GCC 10.
Specifically, one of the main errors I was getting was that none of the apps that load images would work. The error message was `libpng: unsupported zlib version` and this error only went away after doing a `make clean` and full rebuild.
Maybe you don't get the same problem, but building your packages with two different versions of GCC is not a consistent build environment. Please don't open any further issues about your build until you do a full rebuild.
