### ISSUE TITLE
Create a better build system

### ISSUE THREAD

**Issue by Admicos** [joshiemoore/snakeware#14]
In your current build scripts, you seem to be just copying system libraries & hoping for the best, which can fail if the host system is subtly different from what you're using.

To make this better, I suggest using something small like [Buildroot](https://buildroot.org/) or [KISS Linux](https://k1ss.org).

Buildroot is the most mature of the two, and is specifically designed for building embedded Linux systems, which seems like a close goal to what you're doing here. It also has a lot of configuration options and build scripts for a lot of packages, including Python, which can make it feel complicated.

KISS is newer and less mature, but is very simple to understand, as most of the system is good old shell scripts & Busybox. However, it's not designed for a specific purpose like Buildroot, so it would probably only be used as a consistent base system (in a chroot or something similar) for the actual hand crafted build scripts.

So, if you want a robust build system, I'd recommend you go with Buildroot or something similar to it, but if you want your build system to be small, you can try messing around with something like KISS.

**Comment by joshiemoore** [comment]
I agree, copying library files from the host system is disgusting. I will look into buildroot, this looks like exactly what we need. Thank you!

**Comment by jamesalbert** [comment]
@joshiemoore regardless of how we build, I been working this morning on getting the build into github actions with a corresponding local build flow using docker. Did you have other plans?

**Comment by joshiemoore** [comment]
The original build system has been replaced with a build system based on buildroot.
