### ISSUE TITLE
bug when creating the iso image

### ISSUE THREAD

**Issue by donno2048** [joshiemoore/snakeware#142]
when running the build script I get:
```
checking whether mknod can create fifo without root privileges... configure: error: in `/home/brad/CITUR-L/build/buildroot_x86-64/output/build/host-tar-1.29':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
```
obviously I tried  `set FORCE_UNSAFE_CONFIGURE=1` which doesn't worked I also tried other stuff like:

`env FORCE_UNSAFE_CONFIGURE=1` and `export FORCE_UNSAFE_CONFIGURE=1`  and run them as root and nothing worked.

**Comment by karx1** [comment]
I might be misunderstanding, but are you trying to run the build script as root? You shouldn't have to, it works without root for me

**Comment by donno2048** [comment]
oops, my bad
