### ISSUE TITLE
Snakewm is very laggy on VirtualBox, even with 2 virtual cores!

### ISSUE THREAD

**Issue by DGTV11** [joshiemoore/snakeware#161]
Help! Booting snakeware and typing in "snakewm" is ok but when I enter snakewm, it is so laggy that it the mouse only moves very rarely!

**Comment by DGTV11** [comment]
This is the proof:

https://user-images.githubusercontent.com/52272655/119444898-86bc6080-bd5e-11eb-89bc-57f048b5f17d.mov

**Comment by SorrowEater** [comment]
How much RAM do you have allocated? You're going to need a bit more than you would think (4gb-ish)

**Comment by DGTV11** [comment]
> How much RAM do you have allocated? You're going to need a bit more than you would think (4gb-ish)
[
![Uploading Screenshot 2021-06-10 at 3.20.38 PM.png…]()
](url)

**Comment by DGTV11** [comment]
Do I have to redo the ENTIRE VM creation???
Hope not.

**Comment by DGTV11** [comment]
I have 8 GB of ram. I hope I don't have to allocate more than half of my ram!

**Comment by Zireael07** [comment]
For pretty much any VM, 2 GB is like the minimum nowadays. 512 MB is waay too little, AFAIK even DOSBox uses more.
IIRC you can adjust the slider after you created the VM, though.

**Comment by SorrowEater** [comment]
> I have 8 GB of ram. I hope I don't have to allocate more than half of my ram!
> 
> 

You shouldn't have to, but Python is plenty RAM-hungry. snakeware is light, so 2gb is barely enough. I use 4-8gb, more isn't needed.

**Comment by DGTV11** [comment]
2048 MB and 2 virtual cores for snakewm still isn't enough! Do I have to increase it further???
PS: snakeware sometimes duplicate keypresses in the shell
