### ISSUE TITLE
Cannot shutdown system

### ISSUE THREAD

**Issue by karx1** [joshiemoore/snakeware#18]
Hey, how would I shutdown the snakeware system? Running os.system("/sbin/shutdown") in the Python console does not work, and there is currently no way to shutdown the system from snakewm (though I am going to make one), so I am currently relying on force shutdowns, which I would rather not use. So if you could please tell me how to shutdown the system, so I could then build a button for it in snakewm.

**Comment by shazz** [comment]
I hope that snakeware will be as resilient as a C64 and "just switch off" won't corrupt anything :)

**Comment by karx1** [comment]
Yeah, just ended up going with "/sbin/poweroff -f" in the end
