### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by karx1** [joshiemoore/snakeware#24]
Hey, I was trying to build the image so I could test my changes in a qemu to see if it worked reliably with snakeware, but every time the build fails when trying to install GRUB.
![image](https://user-images.githubusercontent.com/49726028/83340888-0118e880-a2a3-11ea-9e5c-29283987062c.png)
Looks like it's failing to mount the EFI partition correctly. Could ths be because I already had some folders there for my NAS?

**Comment by joshiemoore** [comment]
Hello, thanks so much for trying it out! I suggest not trying to build an image with the current build system. We're switching to a new build system based on buildroot, and I'll be pushing that tonight. The current build system only werks reliably on my machine, while the new system should work for everyone (and also enable people to try to build for raspberry pi and whatever else).

In this case though, and this is just a guess, it looks like you already had something else mounted on /mnt when you started the build process. I could be wrong, but I'm not sure.

Also, I saw your PR and it looks good, I'll merge it as soon as I get a chance to try it out
