### ISSUE TITLE
Shutdown/Reboot not working

### ISSUE THREAD

**Issue by joshiemoore** [joshiemoore/snakeware#26]
I have tested the shutdown and reboot dialogs on my host Arch install, while running snakeware in a VM, and running snakeware on real hardware, and they don't seem to work in any of these configurations.

However, if I run `os.system("/sbin/reboot -f")` (or shutdown) from the interpreter, this operation works as expected.

**Comment by ankith26** [comment]
Is python running with sudo privileges, if not then I guess python cannot do a reboot for the system.

**Comment by karx1** [comment]
I don't really know why this is happening. The dialog is just running os.system("...") when you confirm. Maybe it has something to do with SnakeWM permissions?

**Comment by karx1** [comment]
I didn't actually get a chance to test it yesterday because the build was failing, but I'll try and troubleshoot today.
