### ISSUE TITLE
Buildroot dependency missing

### ISSUE THREAD

**Issue by shazz** [joshiemoore/snakeware#29]
Hi,
To get the build working on Ubuntu 18-04, I had to add:
`sudo apt-get install libelf-dev`

Then it finished but with one error: `create: command not found`, but I guess just a missing comment

```
 0+0 records in
0+0 records out
0 bytes copied, 0.0003471 s, 0.0 kB/s
./build.sh: line 47: create: command not found

Welcome to fdisk (util-linux 2.34).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x6f584148.

Command (m for help): Created a new DOS disklabel with disk identifier 0x9431d0e0.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): Partition number (1-4, default 1): First sector (2048-819199, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-819199, default 819199): 
Created a new partition 1 of type 'Linux' and of size 399 MiB.

Command (m for help): Selected partition 1
The bootable flag on partition 1 is enabled now.

Command (m for help): The partition table has been altered.
Syncing disks.


A virtual block device has been created for snakeware.img.
Use lsblk to find the number of this device and run ./img_final.sh <num>
Example: ./img_final.sh 0 for loop0
```

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 8:56 AM +03, shazz wrote:
> Hi,
> To get the build working on Ubuntu 18-04, I had to add:
> `sudo apt-get install libelf-dev`

Buildroot has a list of dependencies it needs in it's manual[1], and I
assume `libelf-dev` is covered by the `build-essential` package in
Debian-based distros, which Ubuntu is.

It also doesn't work on my (albeit _very_ exotic) system configuration,
so I'm planning to make a somewhat reproducible build environment for
easier build setup.

In the meantime, the manual link should be added in the README or a
similar place.

[1]: https://buildroot.org/downloads/manual/manual.html#requirement

**Comment by shazz** [comment]
> Buildroot has a list of dependencies it needs in it's manual[1], and I assume `libelf-dev` is covered by the `build-essential` package in Debian-based distros, which Ubuntu is.

Looks it's not, I have `build-essential` installed but `libelf-dev` was not

**Comment by Admicos** [comment]
On Sun May 31, 2020 at 9:02 AM +03, shazz wrote:
> Looks it's not, I have `build-essential` installed but `libelf-dev` was
> not

Interesting.

Searching about it, it seems like it's about a specific kernel
configuration option that requires libelf:

http://lists.busybox.net/pipermail/buildroot/2018-March/215220.html

> Users who have libelf installed on their system won't see a problem,
> but users who don't have libelf installed will get a build
> failure. Therefore, this commit adds an option that allows a user to
> indicate that his Linux kernel configuration requires libelf. When
> this option is enabled, we add host-elfutils to the dependencies of
> the linux package (host-elfutils provides the libelf library).

But I'd assume this means Buildroot itself would download it on its
own, or am I confusing something.

I admit, I don't have much experience with Buildroot, so this can be
completely expected.

**Comment by shazz** [comment]
Ah I missed another error in the script (which I guess should stop it):

```
>>>   Executing post-build script ../post-build.sh
/home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/../buildroot/output/target/usr/bin/python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by shazz** [comment]
As a workaround I added the last path to `LD_LIBRARY_PATH` 
`export LD_LIBRARY_PATH=/home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/output/target/usr/lib`

Then the compilation of pygame failed due to the fact some host paths (SDL) were in the includes:

```
    /home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/output/host/bin/x86_64-snakeware-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fPIC -D_REENTRANT -DENABLE_NEWBUF=1 -I/usr/X11R6/include -I/usr/include/SDL -I/usr/include/SDL -I/usr/include -I/usr/include -I/home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/output/target/usr/include/python3.8 -c src_c/imageext.c -o build/temp.linux-x86_64-3.8/src_c/imageext.o
    x86_64-snakeware-linux-gnu-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/SDL'
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    error: command '/home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/output/host/bin/x86_64-snakeware-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/../buildroot/output/target/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qa4d6ht6/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qa4d6ht6/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ym2m5lk3/install-record.txt --single-version-externally-managed --compile --install-headers /home/shazz/projects/pythonOS/snakeware/snakeware/buildroot/output/target/usr/include/python3.8/pygame Check the logs for full command output.
```

**Comment by Admicos** [comment]
I am currently working on a script to create a fresh chroot for
snakeware development, which should help with making sure nothing from
the real host bleeds over.

It's almost done. It just needs testing to make sure everything builds
in it. If you are willing to help, I'll upload it somewhere.

**Comment by shazz** [comment]
yes please share!
