### ISSUE TITLE
[feature request] - snaketerm improvements 

### ISSUE THREAD

**Issue by jamesalbert** [joshiemoore/snakeware#3]
Awesome project. I'm running it right now 😎 Just a couple things I noticed while rummaging around:

- If the current output exceeds the height of the output panel, it automatically scrolls all the way up. Keeping the latest output focused is probably the intent.
- No way to clear output
- autocomplete and history (up and down arrow functionality) would be cool, too.

Definitely interested in taking a wack at it this weekend, but wanted to check if there's any work being done on this before I get started.

**Comment by joshiemoore** [comment]
Hi, thank you for checking it out! I noticed the thing with the scrollbar, but moved on before fixing it. It would be amazing if you wanted to work on these changes when you get a chance. Let me know if you have any questions!
