### ISSUE TITLE
Release artifacts could be smaller

### ISSUE THREAD

**Issue by alexandruavadanii** [joshiemoore/snakeware#43]
Not an issue per-se, but an idea about the release artifacts, specifically the raw disk image file:
- archiving the fixed-size disk image (currently 400MB as hardcoded in the source code) using only gzip does reduce its size a bit (103MB with the default compression settings);
- using a sparse disk image format (e.g. qcow2) helps too (222MB with uncompressed qcow2, 111MB with compressed qcow2), but is only useful if people are using the disk image with a virtualization platform or are able to convert the image back to a raw format if they intend to `dd` it to a physical drive;

**Comment by Admicos** [comment]
I have managed to create a live ISO for it in just 56MB. It can probably be smaller if I change the compression algorithm, but I went for boot speed instead of image size.

Not entirely sure if I should send a PR for it, as it's just a part of my random experiments.

**Comment by merwok** [comment]
@joshiemoore could you say if this was implemented or rejected?

**Comment by joshiemoore** [comment]
Well this was basically implemented when we switched to buildroot, the release images are currently quite small at only ~72MB. This issue was related to the old build system so it's quite outdated
