### ISSUE TITLE
Running wm.py on macOS

### ISSUE THREAD

**Issue by sdubois** [joshiemoore/snakeware#44]
I am trying to run wm.py on macOS. I ran pip3 install pygame but I still receive the error "ImportError: No module named pygame"

Is there anything else I need to do to get this running?

**Comment by callmepavo** [comment]
Pygame and pygame GUI are 2 packages required to run the window manager.
I've sent a pull request that adds this explanation to a readme in snakewm, along with the other pip packages you need.

Run:

`python3 -m pip install pygame`

And 

`python3 -m pip install pygame-gui`

**Comment by callmepavo** [comment]
I just realised I misread the part where you installed the packages. Sorry if my reply seemed condescending.

**Comment by sdubois** [comment]
Not at all! I have pygame and pygame-gui installed, but wm.py still returns 

```
Traceback (most recent call last):
  File "wm.py", line 11, in <module>
    import pygame, pygame_gui
ImportError: No module named pygame
```

**Comment by horstjens** [comment]
@sdubois  as you write that you are using MacOS:
can it be that you have pygame installed for python2, but not for python3 ? 
As far as i understand each MacOS has an python2 on board.
You can check by typing in a terminal: 
`python` 
(make sure it says python version 3 something) and then 
`import pygame`
If you still get an error than pygame was installed for python2.

**Comment by sdubois** [comment]
Ah you are right! I was able to get it working by using the python3 command.

**Comment by sdubois** [comment]
Slightly related: I see the instructions say use the left winkey to open the app menu. Is there a way to do that on mac OS?
