### ISSUE TITLE
official forum/subreddit/discord channel ?

### ISSUE THREAD

**Issue by horstjens** [joshiemoore/snakeware#46]
I am very very much excited about this project and want to know a place to discuss / communicate/ get involved into snakeware, other than sending issues or pull requests. 
Is there an official (beginner friendly) forum / place in the internet ?

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 2:02 PM +03, Horst JENS wrote:
> I am very very much excited about this project and want to know a place
> to discuss / communicate/ get involved into snakeware, other than
> sending issues or pull requests.

> Is there an official (beginner friendly) forum / place in the internet ?

I don't think there is anywhere other than this repo here right now.

However, if a discussion place gets created, I would strongly be in
favor of having it in a free software platform, like IRC or Matrix.

Or at least, the ability to bridge via them, so no one needs a heavy
proprietary client like Discord.

**Comment by Abdur-rahmaanJ** [comment]
Yess i'm for it!!! Created one here: https://discord.gg/PhZRVMJ Just notify me youre the one who opened the issue!

**Comment by Abdur-rahmaanJ** [comment]
@Admicos you can have discord on the web. Also pallets for example has an irc to discord bridge

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 2:08 PM +03, Abdur-Rahmaan Janhangeer wrote:
> You can have discord on the web.

I know, but it's still proprietary.

> Also pallets for example has an irc to discord bridge

Yeah, that's one alternative if Discord gets decided as the platform to
use.

**Comment by callmepavo** [comment]
If we did it over IRC then a pure python IRC client could be one of the apps. A more complicated project that would be

**Comment by Abdur-rahmaanJ** [comment]
@callmepavo hexchat??

**Comment by callmepavo** [comment]
@Abdur-rahmaanJ not sure how well that would work with pygame gui

**Comment by callmepavo** [comment]
Yeah that might work

**Comment by dijit** [comment]
On the main page there it says something about snakechat (chat with other snakeware users), there are multiple python libraries for talking over IRC, even one made by a friend of mine which is extensively used (and thus; tested): https://github.com/kylef/irctk

**Comment by John123Allison** [comment]
+1 Discord. I think that would be the most effective and widely adoptable platform, and has capacity for roles.

**Comment by joshiemoore** [comment]
Hi, I agree, a more centralized way to communicate would be good. I don't use or endorse Discord, and I personally feel that no free software project should. Discord is proprietary spyware that sells your data restricts your freedoms.

I would be strongly in favor of IRC. I admittedly haven't put much thought into comms, I wasn't expecting so many smart people to be interested in this in such a short time! :) I have created a channel on Rizon, #snakeware @ irc.rizon.net.

Also, I have no problem with someone creating a snakeware Discord for those that want to use it, my only request is that it not claim to be "official" or representative of the project.

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 7:16 PM +03, Josh Moore wrote:
> I would be strongly in favor of IRC. I admittedly haven't put much
> thought into comms, I wasn't expecting so many smart people to be
> interested in this in such a short time! :) I have created a channel on
> Rizon, #snakeware @ irc.rizon.net.

Nice! Connected and will idle until my ZNC crashes :p

> Also, I have no problem with someone creating a snakeware Discord for
> those that want to use it, my only request is that it not claim to be
> "official" or representative of the project.

Fair enough. My suggestion would be to have an IRC to Discord bridge set
up (IRC side shouldn't need to do anything) so people who prefer Discord
can still communicate with the IRC folks.

**Comment by Abdur-rahmaanJ** [comment]
Anybody who has experience setting up bridges just ping

**Comment by joshiemoore** [comment]
https://discord.gg/yr27Zsy
