### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [joshiemoore/snakeware#47]
Related to #46 and more broad, i think a logo might be nice ^^_

**Comment by callmepavo** [comment]
I like the symbolism of a snake eating its own tail

**Comment by Admicos** [comment]
On Tue Jun 2, 2020 at 2:27 PM +03, callmepavo wrote:
> I like the symbolism of a snake eating its own tail

That might get confused with PyPy, though.

**Comment by joshiemoore** [comment]
Yes, we definitely need a logo. I am not artistic at all unfortunately. If any artists want to create a logo, I would be eternally grateful. We would need a few different resolutions (ie one for the boot screen, an icon, etc.)

My preference is for something that looks kind of "retro" and cool, I think that would be fun. Like those old tech company logos from the 70s/80s. Maybe that's a dumb idea, as long as it looks pretty cool I'll probably be happy with it

**Comment by OIK2** [comment]
Python with a penguin shaped meal in its belly

**Comment by Abdur-rahmaanJ** [comment]
@joshiemoore let me work on some proposals

**Comment by Abdur-rahmaanJ** [comment]
Proposal one: Commodore64 theme with the two things which coincidentally also makes a snake's tongue. Colored those two to python's colors. The line underneath the letters is a reference to slackware meaning  a linux distro

@joshiemoore 

![logo_slackware](https://user-images.githubusercontent.com/22630684/83599436-33656700-a57d-11ea-9028-58fec2c7d32b.png)

**Comment by Abdur-rahmaanJ** [comment]
That's a brute open + commodore + py

![logo_open](https://user-images.githubusercontent.com/22630684/83599535-7d4e4d00-a57d-11ea-8db8-2a6ac095a471.png)

**Comment by Abdur-rahmaanJ** [comment]
Reference

![commodore64](https://user-images.githubusercontent.com/22630684/83599662-ca322380-a57d-11ea-9df3-761f68c45761.png)

**Comment by callmepavo** [comment]
I like the down facing split not only does it work as a reference to c64 but also looks a bit like a snake tongue

**Comment by callmepavo** [comment]
I feel like we should double down on the 2 trapizoids facing down, i like that
