### ISSUE TITLE
Mac OS build fails due to clang and `sed` usage

### ISSUE THREAD

**Issue by omelched** [joshiemoore/snakeware#52]
Hi! My name is Denis, and I tried to build snakeware on my MacBook. But I have had some issues:
- `sed` utility which is obviously in Makefile in `snakeware/snakeware/buildroot` may not be used on macOS with option `-r`. The issue show itself like this:
`(base) user@omelched-MacBook snakeware % sudo ./build.sh x86-64`
`sed: illegal option -- r`
`usage: sed script [-Ealn] [-i extension] [file ...]`
`       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]`
For some reason in macOS this option is renamed to `-E` and replacing that Makefile line 349: `sed -n -r...` with `sed - n -E...` solved that problem for my case. 
Maybe it will be a good idea to do this action in [build.sh](https://github.com/joshiemoore/snakeware/blob/master/snakeware/build.sh) before `make` based on which OS you are building on.
- the second problem is that, for quite obvious reasons, macOS specifies Clang as main compiler and this causes issues because buildroot had to be made with GCC (I presume). Therefore, the issue happens:
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1`
`/Applications/Xcode.app/Contents/Developer/usr/bin/make -j1 O=/Users/user/git_repo/snakeware/snakeware/buildroot/output HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig`
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1`
`You must install 'gcc' on your build machine`
So if we try ti call `/usr/bin/gcc` that would be Clang:
`(base) user@omelched-MacBook snakeware % /usr/bin/gcc`     
`clang: error: no input files`
I'm still stuck on that issue but i think that some manipulation with HOSTCC and HOSTCXX in Makefile to define them as separately installed gcc-9 and g++-9 will help. At least I will try it tomorrow. 
And as that solution will be confirmed I suggest to add some tweaks to support native macOS build too.

Anyway, I'll do my best to help you with this interesting project!

**Comment by joshiemoore** [comment]
Hi, thank you for your interest! MacOS and Windows are not supported dev platforms for this project, we recommend running Linux in a VM or dual-booting, etc.
