### ISSUE TITLE
wiki / docs / user guide

### ISSUE THREAD

**Issue by danielyoureelewis** [joshiemoore/snakeware#57]
I think it would be helpful to start a wiki. Arch linux is well documented due to ArchWiki. I think that would be a good model.

**Comment by callmepavo** [comment]
presumably using github wiki functoin

**Comment by John123Allison** [comment]
+1 GitHub Wiki

**Comment by dargonforce** [comment]
The Snakeware Wiki is now open for contribution

https://github.com/joshiemoore/snakeware/wiki
