### ISSUE TITLE
New Logo Proposals 🍧

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [joshiemoore/snakeware#58]
Refering #47 

Refers to commodore64 logo and theme. The double slits of c64 coincidentally represents a snake's tongue. The lines are a reference to slackware meaning a Linux distro
![logo_slackware](https://user-images.githubusercontent.com/22630684/83653680-1f495600-a5cd-11ea-9a72-4c0c0836ab22.png)

Py + open to the theme of c64
![logo_open](https://user-images.githubusercontent.com/22630684/83653673-1d7f9280-a5cd-11ea-9179-9d786dfb98fc.png)

reference c64
![commodore64](https://user-images.githubusercontent.com/22630684/83654105-ad254100-a5cd-11ea-8e5d-b71e9c39979b.png)

**Comment by Abdur-rahmaanJ** [comment]
@Admicos kind of sleeek 👍

**Comment by callmepavo** [comment]
Similar situation here, build on an ancient computer so decided to start learning inscape.  Very basic attempt at a minimalist type logo.
![logo-with-lines](https://user-images.githubusercontent.com/24368336/83722396-7acc2000-a66f-11ea-8f55-0974f72e8872.png)
![logo-no-lines](https://user-images.githubusercontent.com/24368336/83722401-7e5fa700-a66f-11ea-82ab-fbd015b68c95.png)

**Comment by Abdur-rahmaanJ** [comment]
Me too on Inkscape ^^

**Comment by joshiemoore** [comment]
Thank you all for your ideas, I've been in touch with a graphic designer who is working on a logo for snakeware. Thanks again!
