### ISSUE TITLE
Window manager does not start in release 0.0.3

### ISSUE THREAD

**Issue by ArneBachmann** [joshiemoore/snakeware#61]
```
SnakeWM.run()
Traceback
TypeError: run() missing 1 required positional argument: 'self'
```

**Comment by joshiemoore** [comment]
Hello, you should type:
```
>>> from snakewm.wm import SnakeWM
>>> SnakeWM().run()
```
in the interpreter, and it will run for you.

Also, you could just type `snakewm` by itself and snakewm will start that way too.

**Comment by ArneBachmann** [comment]
My bad, forgot to run the constructor `()` on the class.
