### ISSUE TITLE
Add a discord server

### ISSUE THREAD

**Issue by Dragon20C** [joshiemoore/snakeware#63]
Make it easier to communicate with everyone and share ideas etc

**Comment by Abdur-rahmaanJ** [comment]
See #46 and @joshiemoore 's answer to the one we created https://discord.gg/PhZRVMJ

**Comment by joshiemoore** [comment]
I've changed my attitude on this. Discord has been more requested than any actual snakeware feature, and people are definitely more inclined to use Discord than IRC. I also think something feels wrong about someone other than me owning/maintaining a Discord for the project. I'm going to make an "official" snakeware discord tomorrow so folks can hop on

**Comment by Abdur-rahmaanJ** [comment]
@joshiemoore or i can change owner for the server i created like some people already joined ^^_ Besides please check the logo issue.

**Comment by Dragon20C** [comment]
@joshiemoore I think its a good idea discord is extremely popular and I rather not have another app/program to communicate with people, I completely understand people why they dont want to use discord because of the data they can get from the users, but discord is extremely popular and I think it cant be ignored, Cant wait to join the discord server!
Should it be safe to close this now?

**Comment by Admicos** [comment]
On Thu Jun 4, 2020 at 3:55 AM +03, Josh Moore wrote:
> I've changed my attitude on this. Discord has been more requested than
> any actual snakeware feature, and people are definitely more inclined to
> use Discord than IRC. I also think something feels wrong about someone
> other than me owning/maintaining a Discord for the project. I'm going to
> make an "official" snakeware discord tomorrow so folks can hop on

If you want to keep the IRC as well, I might be able to host a bridge
between the two.

**Comment by Abdur-rahmaanJ** [comment]
@Admicos it's a nice thing to keep the IRC! It costs nothing

**Comment by joshiemoore** [comment]
https://discord.gg/yr27Zsy
