### ISSUE TITLE
I want to contribute a game

### ISSUE THREAD

**Issue by ankith26** [joshiemoore/snakeware#7]
I have written a game with python and pygame. 
Do take a [look](http://github.com/ankith26/My-PyChess).

It’s a fairly medium sized project. If you like the project a lot, you could integrate it within your Snakeware Project. And you had mentioned that some changes will be needed to make it work in your project. **If you like my project**, we can work together to to integrate it in yours.

**Comment by joshiemoore** [comment]
Hi, I'm closing this for now, but feel free to send a PR and add your game!
