### ISSUE TITLE
Add new packages for networking support

### ISSUE THREAD

**Issue by lmagoncalo** [joshiemoore/snakeware#84]
I'm trying to work on a web browser and I was wandering if it is possible to add a new package into the snakewm like [requests](https://pypi.org/project/requests/)

**Comment by Admicos** [comment]
> I'm trying to work on a web browser and I was wandering if it is possible to add a new package into the snakewm like requests (https://pypi.org/project/requests/)

While I'm not entirely sure on Josh's view on new packages, extra Pip packages can be added to the snakeware bootable image relatively easily. (And if network support is planned, requests seems like an essential package to have)

ps: From the issue title, it feels like you're asking if snakeware works inside a web browser. You might want to change that to clarify it a little bit.

**Comment by joshiemoore** [comment]
We can definitely add more packages, we're working on installing packages in a cross-platform way during the build process as we plan to target Raspberry Pi in addition to x86. That said, you'll probably want to hold off on implementing a full web browser until we get networking in place, but you could definitely get started on an HTML parser/renderer

**Comment by lmagoncalo** [comment]
Ok, was working on exactly that, trying to render simple html webpages.

**Comment by Abdur-rahmaanJ** [comment]
@lmagoncalo see py browser engines

**Comment by whitelynx** [comment]
One possibility would be to use QtWebEngine via PySide2 (Qt for Python).
Qt can render into an SDL OpenGL context: https://forum.qt.io/topic/68383/qtquick-into-an-sdl2-window/4
PySide2 doesn't yet support cross-compiling for ARM, but it can actually built inside an ARM environment. (see https://bugreports.qt.io/browse/PYSIDE-802)

**Comment by Admicos** [comment]
> One possibility would be to use QtWebEngine via PySide2 (Qt for
> Python). 

QtWebEngine is WebKit (or Blink, not sure), yeah?

I'm not entirely sure if embedding an entire browser engine larger than
the OS itself would be a great idea, especially on lower-end computers.

Something like NetSurf would probably be better, assuming you don't
mind it taking over the entire framebuffer and running fullscreen.

>Qt can render into an SDL OpenGL context:
> https://forum.qt.io/topic/68383/qtquick-into-an-sdl2-window/4 PySide2

Currently, Snakeware doesn't use OpenGL, but rather draw directly into
the framebuffer.

> doesn't yet support cross-compiling for ARM, but it can actually
> built inside an ARM environment. (see
> https://bugreports.qt.io/browse/PYSIDE-802)

Might be an issue for Raspberry Pi builds, as do you really want to
compile something big like Qt (and something even bigger, like WebKit)
_in_ a Pi?
