### ISSUE TITLE
build: Allow building the disk image without root access

### ISSUE THREAD

**Issue by alexandruavadanii** [joshiemoore/snakeware#88]
The current build implementation leverages `kpartx` and loop devices to copy the rootfs contents to the final disk image, together with a manual step of determining the loop device index.
Instead, we could use FUSE and/or libguestfstools and have the build process work strictly in userspace.
This would add another build dependency.
Also, I'm not sure how this would work with `grub-install` (I hope it will just work), since I previously had issues with `grub-install` on loop device partitions and had to add another level of abstraction using `nbd`.
I'll try to investigate this myself and report here anything useful that I find.

**Comment by joshiemoore** [comment]
See #98
