### ISSUE TITLE
Sample Github pages website for the Snakeware OS

### ISSUE THREAD

**Issue by AdityaJ7** [joshiemoore/snakeware#93]
Hey Everyone,
I have made a sample website for the OS.
I would appreciate if you guys can have a look at it,
I would be happy to receive suggestions.
Here is the link:-
[https://adityaj7.github.io/snakeware.github.io/](URL)

**Comment by joshiemoore** [comment]
Thanks, but I would prefer people didn't make websites. If it ends up that snakeware needs a website I'll put one up. I would want it to be a legit thing, not hosted on github.

**Comment by AdityaJ7** [comment]
ok thanks for letting me know
