### ISSUE TITLE
Add metrics to CPU app

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [joshiemoore/snakeware#99]
CPU app shows only graph with no label as to what fluctuations depict

**Comment by mdoege** [comment]
The graph goes from 0% at the bottom to 100% at the top, showing combined CPU use of all cores/threads. It's 100 px high, so each pixel vertically equals one percent. This is for all threads combined, so e.g. if on my Ryzen with its 16 threads there are 8 threads running at 100% and the other 8 are idle, the graph would show 50% total CPU use.

Horizontally, the graph is 200px wide, so being set to 4 FPS, it shows the last 50 s.

**Comment by joshiemoore** [comment]
I would be okay with leaving it as it currently is, I think it works really well to get general estimates of CPU usage, I've been using it a lot during testing. @mdoege I'll leave it up to you to decide whether you want to add a numerical display to this.

**Comment by mdoege** [comment]
Cpumon is not meant to be a tool for precise measurement anyway, just something small and unobtrusive to keep in the corner of your desktop. So I would prefer to keep it visually as clean and simple as possible.

Perhaps snakewm needs a basic help system for some  usage info about an app to answer questions like this. You know, press F1 and up pops a little text window with a short README. If that key press is handled by the WM, apps would not even have to know about it or implement anything help-related themselves...
